language: python

python:
- 3.6
- 3.7
- 3.8
- 3.9

before_install:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
install:
- pip install -r requirements.txt

script: pytest

branches:
  only:
  - main
  - dev

jobs:
  include:
  - stage: deploy
    name: Deploy to Pypi
    python:
    - 3.9
    deploy:
      provider: pypi
      username:
        secure: cdh7EQi8ur0ukhF8NmF248WTpOk/1tZHSbu2RP/f8QfnqC6qrrA07gYZFed1z2SRAGGHXnLgizft3Yd3M3X/7U2rZAjNDoBs5XAOadjDf9cRq5JF/tEEJYfWivGp4PGJhIhruvymXgi6trKH24RQem/Eto5HnJ4sDdfIn/2rOPe7+lnO9KRJdzGTXiIYhn9+X+H6ELWqvn4XJyYSMv32acNTjdAB+919FOs4arLScDc/afB5lsN7jwCHKbdSNTVMVC6scGXIqx769UKTooRHXKDExC4pVqMcraf6ZBRAKmFOcReK4dQqWMeHq0+tXFaalIsnBMH+JkDwZ7zjP51laXdjyXMPFJNyovzEiVjG/S2X2hAXdp5EpRffBFNlFhrT14Ol3fxjg4ds1RXtl1YO3YPEJFEr/Q3aNI8sJBNphj/kG96JT01XQlfq2E9w60SxprOrpy3OTwXT/mzo2LLpsf8SprJU61i9Fwt7n0nTAWyHdc59FO+LfafLN8bNinupD9cS2wKy+7TCFvPb2D80nbxkyU1I1NjX9iIphKjiORBm4Za+rVl7e7v3tk6cpni7qRHX44oT3sr6SPT90OxsvC0JjsyiKMgXyN9w1zrQlxIEugbOKvWh0U6urP9bB9b2MbBX1Gyy9wAi8brgSvmdgj+5Ew5Ng69lj/NsKDYn8gatY=
      password:
        secure: Je0SNtZ1PR+eQz5wP8Fdr8NQdONkHCd+puL75ojP+pO7Ly3xi1hfE0F1rNXDLCfqT+RTfhwLshOPT8ptawXMvzVNjEQoU2yFcG+5szPPpF+MgGv04fhpNL/qc6L5Id5IkRTo8XQpRfnJWTWOJLZmxbeKpqtRDd0z/wVkSvHhKMFjl1k2zrqXuzOOLAQRvKZp1VoOqDxhvgv9ZRYe6TlDNi9Jxl5WCKhKHCIOlEJLIP1SmDWZTZvuwAE8Fvjvfqw8Z3ljNfImLoXjd47UcaGOv783ZCjyOBhMKWLsZTK8S90AyYaZhrElk2UjuhU4O2P9R1EY18Bh9qvuT/y0MMXzJ/mOETlVI99ZD8HiptlicutECVRFE7aljXU5B/5k7IyyakIpQF1wDuvnYM5XKjb6n+nHkaqQNnfS7iJzcwRO6noNiSTOFqD2bqrVCM1KKQCOMFOh7+MKnneMFvkU4zUtTv0SKOzv/Cjp1B4/u2I9PNa933UYZOSb1LgZshcXULf0qEEzRgVcTiqmAeNa9nySbDgkZ6wCNt5u3W2VTo0P8z88Q2h5fIYvPNCnRcjAQMgiMZeWP7YWe+bYQ47u+uZdOBFzhLyJCPb8Thg2GtDKIk71ufCJplbRC0CfFGnmBYiP3YrMpZJpBsuZ+kmVQQnLh8Q4dlYYgMVct4r/YGYmPXw=
      on:
        branch: main
        python: '3.9'

after_success:
- "./send.sh success $WEBHOOK"
after_failure:
- "./send.sh failure $WEBHOOK"
