language: python

before_install:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh

install:
- pip install -r requirements.txt

branches:
  only:
    - main
    - dev

jobs:
  include:
    - stage: test
      name: Unit Test
      python:
        - 3.8
        - 3.7
        - 3.6
      script: pytest

    - stage: deploy
      name: Deploy to Pypi
      python:
        - 3.9
      deploy:
        provider: pypi
        user: "Elton_Chou"
        password:
          secure: Je0SNtZ1PR+eQz5wP8Fdr8NQdONkHCd+puL75ojP+pO7Ly3xi1hfE0F1rNXDLCfqT+RTfhwLshOPT8ptawXMvzVNjEQoU2yFcG+5szPPpF+MgGv04fhpNL/qc6L5Id5IkRTo8XQpRfnJWTWOJLZmxbeKpqtRDd0z/wVkSvHhKMFjl1k2zrqXuzOOLAQRvKZp1VoOqDxhvgv9ZRYe6TlDNi9Jxl5WCKhKHCIOlEJLIP1SmDWZTZvuwAE8Fvjvfqw8Z3ljNfImLoXjd47UcaGOv783ZCjyOBhMKWLsZTK8S90AyYaZhrElk2UjuhU4O2P9R1EY18Bh9qvuT/y0MMXzJ/mOETlVI99ZD8HiptlicutECVRFE7aljXU5B/5k7IyyakIpQF1wDuvnYM5XKjb6n+nHkaqQNnfS7iJzcwRO6noNiSTOFqD2bqrVCM1KKQCOMFOh7+MKnneMFvkU4zUtTv0SKOzv/Cjp1B4/u2I9PNa933UYZOSb1LgZshcXULf0qEEzRgVcTiqmAeNa9nySbDgkZ6wCNt5u3W2VTo0P8z88Q2h5fIYvPNCnRcjAQMgiMZeWP7YWe+bYQ47u+uZdOBFzhLyJCPb8Thg2GtDKIk71ufCJplbRC0CfFGnmBYiP3YrMpZJpBsuZ+kmVQQnLh8Q4dlYYgMVct4r/YGYmPXw=
        on:
          branch: main
          python: '3.9'

after_success:
  - ./send.sh success $WEBHOOK
after_failure:
  - ./send.sh failure $WEBHOOK