# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
    - main
    - develope
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Test Success
      uses: rjstone/discord-webhook-notify@v1.0.4
      if: ${{ success() && github.event_name == 'push' }}
      with:
        severity: info
        details: Test Succeeded! (Python ${{ matrix.python-version }})
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Test Failure
      uses: rjstone/discord-webhook-notify@v1.0.4
      if: ${{ failure() && github.event_name == 'push' }}
      with:
        severity: error
        details: Test Error! (Python ${{ matrix.python-version }})
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Merge develope -> main
      uses: actions/checkout@master
      if: ${{ github.ref == 'refs/heads/develope' && matrix.python-version = '3.9' }}
      with:
        type: now
        target_branch: main
        github_token: ${{ github.token }}